### PR TITLE
path2d unit movement

### PR DESCRIPTION
**Pull request by sthalik**
See the commit message for caveats and why the implementation is convoluted.

### CODE REVIEW

**Comment by sthalik** [comment]
Node, the previous description about using a different Tween is incorrect. There's a bug where distinct instances of `Path2D` clear themselves if only one of them is cleared.

I worked around the Tween issue with a fake node and a handler for `Tween::tween_updated`.

**Comment by Zireael07** [comment]
Commit messages should be short (ideally <80 characters), so the problem description should be moved to PR description on Github itself.

**Comment by AI0867** [comment]
> Commit messages should be short (ideally <80 characters), so the problem description should be moved to PR description on Github itself.

What? No!

The *title* of a commit message should be short, but the body should contain all necessary explanation.

The commit message ends up in the repository. The PR does not. If you wonder why something was done 10 years later, you don't want to find a short commit message referencing some external resource that may no longer exist.

**Comment by Xrayez** [comment]
It would be nice for the PR to replicate commit message at least, win-win!

**Comment by Byteron** [comment]
Doesn't look like we will merge this, so I'm closing it.

**Comment by Xrayez** [comment]
@Byteron was there any discussion prior to this regarding the decision to close the PR?

**Pull request closed without merging**
