### PR TITLE
Added Development environment setup documentation. 

### PR DESCRIPTION
**Pull request by derkus**
This should help a new contributor get into the project a bit quicker.

### CODE REVIEW

**Comment by jay20162016** [comment]
This definitely helps, but I think a git clone and open method would be easier to setup with git pull requests

**Comment by Byteron** [comment]
Woho! Thanks for that, that's helpful.
I wonder if this maybe can just be put into the CONTRIBUTING.md directly, as setting up the environment is always the first step if you want to contribute.

**Comment by Byteron** [comment]
Oh yes, and if you want to contribute you'll have to do that from a fork, since you need to be authorized to push directly to the project.

So Maybe after downloading the repository, add another step explaining how to create a fork (hitting the fork button) and then how to add the fork to the local repository (`git remote add <user><fork.link>`)
then push changes to `git push <user> <branch>` and create PRs on github.
(I hope that's correct)

**Comment by Byteron** [comment]
Well I guess we can complete it ourselves. Thanks for setting this up, I'll merge it.

**Pull request merged**
