### PR TITLE
mods (insecure, but prototype)

### PR DESCRIPTION
**Pull request by jay20162016**
Plus, most major games with modding don't have sandboxing anyway.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
As long as someone volunteers to explain to players when an add-on they downloaded from our servers deleted a bunch of their files or other malicious actions.

**Comment by Zireael07** [comment]
I don't think .pck files can delete files?

**Comment by jay20162016** [comment]
.pck files can perform malicious actions... but this is just a prototype. Because Godot (as of the moment) has no sandboxing, this is probably the best we can do. However, I don't think we need someone to explain malicious mods, as long we provide a notice that mods can be malicious. And again, most major games with modding support do this too.

**Comment by jay20162016** [comment]
Whops, accidentally pushed some unrelated stuff...

**Comment by jay20162016** [comment]
I'll split the pr in to event parts and mod parts.

**Pull request closed without merging**
