### PR TITLE
Validate map size before enabling creation

### PR DESCRIPTION
**Pull request by coelhucas**
Simple update made to prevent crashes and get familiarized with the project architecture before making further contributions.

Peek 2020-11-25 15-30

I'm willing to add also a dialog to save and load map files onto the editor once I have time. Let me know of any changes needed in this PR.

### CODE REVIEW

**Comment by Byteron** [comment]
Hi!
Can you check the line edit input also for being numerical?
Otherwise it'll crash on parsing to int when the string contains letters I think.

You can use `String.is_valid_integer()`

**Comment by coelhucas** [comment]
I made a update to fix a problem in the validation, but about this `is_valid_integer`, I don't think it's truly necessary. When a cast occurs, any other character is ignored, so:
```gdscript
int("abcde") = 0
int("12a3") = 123
int("dwjao8awujd8aw") = 88
```
(I made these and other tests to ensure it's fine)

But if you think it's better regardless of this, I can add it

**Comment by Byteron** [comment]
oh I didn't know that! Nice!
Then it's ready to go in. :)

**Comment by Byteron** [comment]
Thanks!

**Pull request merged**
